### ISSUE TITLE
Improve Slack Message?

### ISSUE THREAD

**Issue by dbpolito** [firework/deployer#40]
https://api.slack.com/docs/message-attachments

**Comment by wesleyhf** [comment]
Change the normal text to slack message to show more details about the deploy?

**Comment by dbpolito** [comment]
I think we can improve the looking of the messages:

![image](https://cloud.githubusercontent.com/assets/347400/16816087/f5a6375c-4912-11e6-99ed-4999d298ef2a.png)

![image](https://cloud.githubusercontent.com/assets/347400/16816104/01a7456e-4913-11e6-8d0b-02f6bb5631f5.png)

There are also other formatting..

**Comment by wesleyhf** [comment]
Nice :+1:

**Comment by gabrielboliveira** [comment]
@dbpolito I think we can close this issue
